# Generated by Django 2.0.6 on 2019-03-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big2App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newentry',
            old_name='relatedContent',
            new_name='authour',
        ),
        migrations.AlterField(
            model_name='addrelatedcontent',
            name='parentPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='big2App.NewEntry'),
        ),
    ]
